### ISSUE TITLE
Could you please share the source code? Thanks a lot!

### ISSUE THREAD

**Issue by weisswurstkanone** [AlbertoMGV/ScreenResolutionChanger#1]

**Comment by LucBerge** [comment]
@AlbertoMGV I would be interested in the source code as well. Thank you.

**Comment by LucBerge** [comment]
@weisswurstkanone I emailed @AlbertoMGV for the source code here is his answer:

> Hi Lucas,
>
>
> Glad to hear you found it useful! QRes is a VERY old application, as it was originally developed for Win95-98. However, it is still supported in more current versions. The Qres application was discontinued in 2005. More information about the application can be found [HERE](https://qres.sourceforge.net/). If you want to download the source code you can do it from [HERE](https://sourceforge.net/projects/qres/files/qres/QRes%20source%20code%201.0.9.7/).
>
> Thank you very much, and whatever you need don't hesitate to contact me!
